name: mina-credit-score-signer
region: nyc
services:
  - environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: jackryanservia/mina-credit-score-signer
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    name: mina-credit-score-signer
    routes:
      - path: /
    run_command: npm start
    source_dir: /
